First step towards forklifting some go-ipfs configuration functionality into estuary
application-research/estuary pull request #130
Opened 2022-03-21 17:25 UTC by softwareplumber

estuary/node is configured by a  Config struct in the node package, which has some function pointers which allow initialization code specific to estuary or estuary-shuttle to be injected.

This PR removes the function pointers from Config and moves it into a config package, where additional functionality (notably for reading/writing a json confif file) will be added.

Function pointers are replaced by an interface defined in node which we implement independently for estuary and estuary-shuttle

2022-03-21 18:14 UTC, gmelodie requested changes
Just one small comment, overall looking good! Thank you for putting this in place!

2022-03-21 18:15 UTC, gmelodie commented on node/node.go
> +		libp2p.ResourceManager(rcm),
I forgot to highlight the lines above these ones but consider them in this comment as well.

2022-03-21 19:49 UTC, softwareplumber commented on node/node.go
> +		libp2p.ResourceManager(rcm),
You're right, this is me rolling back d00e817f93b9657d3be640e078ddf8a545cd8135 so I could do some testing without taking down internet connectivity for my entire company! I'll happily roll back those changes but the resulting build will not be tested locally.

2022-03-21 21:03 UTC, softwareplumber commented
Latest push creates a config option 'NoLimiter' which defaults to true; when true, the NullResourceManager is used so functionality should be unchanged by this PR

2022-03-23 20:34 UTC, jimmylee reviewed
LGTM, gonna get @whyrusleeping to look at this as well.

2022-03-28 20:16 UTC, merged