Redirect when found preferred upload endpoint on /content/add
application-research/estuary pull request #175
Opened 2022-05-02 19:46 UTC by gmelodie

Adds the functionality requested in #153

2022-05-02 19:48 UTC, jimmylee approved these changes
LGTM

2022-05-02 21:06 UTC, en0ma commented on handlers.go
> +			uep = []string{"http://localhost:3005/content/add"}
you missed removing this @gmelodie

2022-05-03 17:05 UTC, gmelodie commented on handlers.go
> +			uep = []string{"http://localhost:3005/content/add"}
*shyface*

2022-05-03 17:25 UTC, en0ma approved these changes
LGTM

2022-05-03 17:25 UTC, en0ma approved these changes
LGTM

2022-05-03 21:20 UTC, whyrusleeping requested changes
Redirects don't work for uploads unfortunately, this will just result in a broken request.

2022-05-09 12:56 UTC, merged