Merge /collections/content and /fs/list endpoints
application-research/estuary pull request #264
Opened 2022-06-09 13:45 UTC by gmelodie

Fixes #164

2022-06-09 14:35 UTC, jlogelin requested changes

2022-06-09 15:06 UTC, en0ma commented on handlers.go
> +	cols.GET("/content", withUser(s.handleGetCollectionContents))
that was why I suggested this https://github.com/application-research/estuary/issues/164#issuecomment-1151011818

2022-06-09 15:23 UTC, jlogelin reviewed
Friendly reminder: changes to the REST API requires a manual update to the swagger docs via `make generate-swagger`. (Hopefully, this will be added to the pipelines in the near future)

2022-06-09 16:11 UTC, gmelodie commented on handlers.go
> +	cols.GET("/content", withUser(s.handleGetCollectionContents))
Yes there is. It's how most of the other API endpoints that accepts `coluuid` and `colpath` work.

2022-06-10 11:51 UTC, en0ma commented on handlers.go
> +	cols.GET("/content", withUser(s.handleGetCollectionContents))
@gmelodie the `content/add` and `content/add-car` are different (content is the main resource, so collection can come in as query param). But for this, `collection` is the main resource, so it should not be a query param

2022-06-10 16:57 UTC, gmelodie commented on handlers.go
> +	cols.GET("/content", withUser(s.handleGetCollectionContents))
I think the API is due some redesign, but for now the way our users seem to be thinking is that `coluuid` and `colpath` are query params (they don't seem to care what the main resource is). Maybe we could leave them as query params now and later we could do a v2 of the api that's properly RESTful

2022-06-12 17:48 UTC, alvin-reyes commented on handlers.go
> +			// Name: filepath.Base(relp),
Remove the // Name here

2022-06-12 17:48 UTC, alvin-reyes commented on handlers.go
> +	return c.JSON(200, out)
use `http.StatusOk`

2022-06-12 17:49 UTC, alvin-reyes commented on handlers.go
> +		return c.JSON(200, refs)
use `http.StatusOk`

2022-06-12 17:49 UTC, alvin-reyes commented on handlers.go
> +			return err
Let's return the proper http status with a message.

2022-06-13 13:51 UTC, en0ma commented
@gmelodie please address conflict and @alvin-reyes comments so this can be approved and merged

2022-06-14 21:36 UTC, alvin-reyes approved these changes
The docs/docs.go, and swagger.json/yaml will be auto-generated by build process once it's on the main branch.

LGTM.

2022-06-16 05:07 UTC, merged