clarify difference between --no-storage-cron and --disable-deal-making
application-research/estuary pull request #388
Opened 2022-08-03 23:58 UTC by toastts

- Changed the name of the `--disable-deal-making` flag to `--disable-new-deals` for clarity, edited the help message 
- Changed the description of the `--no-storage-cron`, left the name of the flag as is because it seems clear as is if you know what cron means, if not it can be changed

2022-08-04 02:05 UTC, alvin-reyes commented
Good change. @gmelodie, please hold off on merging this since this will require a change on the flags we set on our environments.

2022-08-04 16:47 UTC, gmelodie requested changes

2022-08-04 16:47 UTC, gmelodie commented on main.go
>  			Name:  "no-storage-cron",
I would like to see this flag's name changed too. `storage-cron` doesn't tell me much

2022-08-15 10:49 UTC, gmelodie requested changes
Let's do `disable-deals-storage` and keep `disable-deal-making`.

2022-08-18 19:31 UTC, gmelodie commented
@toastts quick ping on this

2022-08-18 19:53 UTC, toastts commented
Sorry, accidentally pushed to a different remote and didn't realize it didn't update this branch for the PR 😅. Change should be up now on this branch

2022-08-25 16:27 UTC, gmelodie submitted a review, later dismissed

2022-09-05 13:46 UTC, gmelodie approved these changes

2022-09-05 13:46 UTC, merged