feat: wire tracing across rpc boundaries
application-research/estuary pull request #40
Opened 2021-09-14 18:48 UTC by frrist

2021-09-17 23:08 UTC, frrist commented on cmd/estuary-shuttle/main.go
> -var Tracer = otel.Tracer("shuttle")
this moved onto the Shuttle struture so they can be viewed independently, i.e. which shuttle produced which trace.

2021-09-17 23:09 UTC, frrist commented on cmd/estuary-shuttle/main.go
> +		if cctx.Bool("jaeger-tracing") {
allows estuary/shuttles to send traces to a jaeger endpoint. Disabled by default.

2021-09-17 23:09 UTC, frrist commented on cmd/estuary-shuttle/main.go
> -func (d *Shuttle) RunRpcConnection() error {
consistency, sorry for the extra diff.

2021-09-17 23:11 UTC, frrist commented on cmd/estuary-shuttle/rpc.go
> +	// If the command contains a trace continue it here.
Here is where the shuttle continues the trace if present in the command from Estuary.

2021-09-17 23:13 UTC, frrist commented on cmd/estuary-shuttle/rpc.go
> +			TraceCarrier: drpc.NewTraceCarrier(span.SpanContext()),
Here is one example of how the shuttle passes the trace context back to estuary.

2021-09-17 23:15 UTC, frrist commented on drpc/traceing.go
> +OpenTelemetry spec dictates trace.SpanContext must be read only, and therefore does not implement a
Bit annoying, but below is the workaround for this.

2021-09-17 23:16 UTC, frrist commented on main.go
> +func init() {
allows estuary to be started without a lotus node running on the same machine.

2021-09-17 23:16 UTC, frrist commented on shuttle.go
> +	if msg.HasTraceCarrier() {
Here is where Estuary will continue a trace if one is present in the message received from the shuttle.

2021-09-28 17:58 UTC, whyrusleeping commented on cmd/estuary-shuttle/main.go
> +			Name:  "jaeger-provider-port",
would be nice to combine all these flags into one (or two, to set the sampler ratio separately)

2021-09-28 18:23 UTC, whyrusleeping commented on cmd/estuary-shuttle/rpc.go
> +			span.AddEvent("detected previous pin failure, resend notification")
im wondering how much extra load will be generated by these events...

2021-09-28 18:24 UTC, whyrusleeping commented on cmd/estuary-shuttle/rpc.go
> +	return s.sendRpcMessage(ctx, &drpc.Message{
Maybe we should just set the TraceCarrier in the sendRpcMessage method?

2021-09-28 18:36 UTC, whyrusleeping commented on main.go
> +		&cli.IntFlag{
same comment about making this fewer flags

2021-09-28 18:36 UTC, whyrusleeping requested changes
A few small changes requested, otherwise looks great, thanks @frrist !

2021-11-04 17:02 UTC, whyrusleeping approved these changes
lgtm

2021-11-04 17:02 UTC, merged