add rustup to requirements and a note about libhwloc-dev on linux
application-research/estuary pull request #439
Opened 2022-09-15 05:34 UTC by 44203

just a couple of readme updates when setting up from scratch on ubuntu

2022-09-16 16:14 UTC, en0ma submitted a review, later dismissed

2022-09-16 19:45 UTC, gmelodie requested changes

2022-09-16 19:45 UTC, gmelodie commented on README.md
> +On Ubuntu, install `libhwloc-dev`.
This should be in the same line as `- [hwloc](https://www.open-mpi.org/projects/hwloc/)`

2022-09-16 19:45 UTC, gmelodie commented
Also why do we need `rustup`?

2022-09-16 19:48 UTC, 44203 commented
> Also why do we need `rustup`?

Unsure, but running `make clean all` fails if it isn't installed and asks for it.

2022-09-26 13:49 UTC, alvin-reyes commented
Please move use `dev` as the upstream branch for this PR.

2022-09-30 21:10 UTC, merged