bugfix for mac silicon - makes sure homebrew path is in library path
application-research/estuary pull request #454
Opened 2022-10-08 02:43 UTC by snissn

seems homebrew's library path not being added to LIBRARY_PATH is a recurring issue and this should fix it

2022-10-08 05:11 UTC, jimmylee approved these changes
LGTM, seems fine.

2022-10-09 22:09 UTC, alvin-reyes requested changes
Looks good. Can we instead have a flag here like `BUILD_ENV=mac` or `INCLUDE_HOMEBREW=true`? 

then add the following on the Makefile
```
ifeq ($(BUILD_ENV),"mac")
	export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)
endif
```

OR

```
ifeq ($(INCLUDE_HOMEBREW),"true")
	export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)
endif
```

2022-10-11 02:01 UTC, snissn commented
> Looks good. Can we instead have a flag here like `BUILD_ENV=mac` or `INCLUDE_HOMEBREW=true`?
> 
> then add the following on the Makefile
> 
> ```
> ifeq ($(BUILD_ENV),"mac")
> 	export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)
> endif
> ```
> 
> OR
> 
> ```
> ifeq ($(INCLUDE_HOMEBREW),"true")
> 	export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)
> endif
> ```

I don't understand -- is BUILD_ENV or INCLUDE_HOMEBREW a variable that the make chain understands? Thanks

2022-10-16 14:32 UTC, alvin-reyes commented
It'll be a variable that the make chain will understand when you pass it. You then parse the variable and set the LIBRARY path based on the value.

The goal is to allow the developer to build it specifically for mac/m1 and not force any non-mac users to export a non-existent path.
```
make all BUILD_ENV=mac 

OR 

make all INCLUDE_HOMEBREW=true
```

> > Looks good. Can we instead have a flag here like `BUILD_ENV=mac` or `INCLUDE_HOMEBREW=true`?
> > then add the following on the Makefile
> > ```
> > ifeq ($(BUILD_ENV),"mac")
> > 	export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)
> > endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > OR
> > ```
> > ifeq ($(INCLUDE_HOMEBREW),"true")
> > 	export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)
> > endif
> > ```
> 
> I don't understand -- is BUILD_ENV or INCLUDE_HOMEBREW a variable that the make chain understands? Thanks

2022-11-09 21:17 UTC, snissn commented
Hey! I didn't notice your comment until now, sorry! 

So is the idea that a user who's building estuary will know to add an environment flag when compiling estuary and will type `make all BUILD_ENV=mac` into the shell? That feels like a source of error and confusion for people compiling this, and is about as confusing as requiring a user anyway to know that they need to add the homebrew path to LIBRARY_PATH

> not force any non-mac users to export a non-existent path.

My understanding of the unix philosophy and how path works is that it's not a problem to append non existence paths to the LIBRARY_PATH variable, this PR just simply says to the make chain in addition to all the random folders you're checking that may or may not have the library you're looking for also check /opt/homebrew/lib

https://unix.stackexchange.com/questions/96577/is-there-a-problem-if-i-add-a-non-existing-path-to-path-environment-variable

the code appends  /opt/homebrew/lib to LIBRARY_PATH it doesn't replace it 

```export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)``` 

IMO this PR just makes a build problem go away automatically with essentially 0 downside except an extra few system calls in the build chain to potentially learn a directory doesn't exist

2022-11-09 22:49 UTC, alvin-reyes commented
`
So is the idea that a user who's building estuary will know to add an environment flag when compiling estuary and will type make all BUILD_ENV=mac into the shell? That feels like a source of error and confusion for people compiling this, and is about as confusing as requiring a user anyway to know that they need to add the homebrew path to LIBRARY_PATH
`

I don't see why this would confusing. If you are building on a mac, it make sense to check if there are mac specific libraries you need to add. Same if we will eventually support windows. 

`
My understanding of the unix philosophy and how path works is that it's not a problem to append non existence paths to the LIBRARY_PATH variable, this PR just simply says to the make chain in addition to all the random folders you're checking that may or may not have the library you're looking for also check /opt/homebrew/lib
`

It won't be an issue if the path doesn't exist. It will be when it actually exist. Given `homebrew` might never be on any linux system other than Mac. 

I think its better to auto-detect it then rather that forcing it. It's much cleaner and we can add more conditions to it per operating system.

```
ifeq ($(OS),Darwin)
	export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)
endif
```

2022-11-09 23:12 UTC, snissn commented
wow awsome!! thanks 
```
ifeq ($(OS),Darwin)
	export LIBRARY_PATH := /opt/homebrew/lib:$(LIBRARY_PATH)
endif
```

is perfect! I'll update the PR

2022-11-14 09:47 UTC, en0ma approved these changes

2022-11-18 19:04 UTC, en0ma commented
@alvin-reyes can you have a final look at this, so we can get it in

2022-11-22 00:42 UTC, snissn reviewed
I think my second commit https://github.com/application-research/estuary/pull/454/commits/b0a1efca9ca61de57091332a29b9958df47610e6 addresses this -- 

@alvin-reyes  can you please confirm?

2022-12-06 15:36 UTC, snissn commented
@alvin-reyes I think that this has been ready to be merged and your concerns were addressed

2022-12-18 07:29 UTC, alvin-reyes approved these changes

2022-12-18 07:29 UTC, merged