Restify /contents API
application-research/estuary pull request #600
Opened 2022-11-28 14:22 UTC by gmelodie

Addresses #583

2022-12-05 19:28 UTC, kelindi commented
@gmelodie Could we have the car files be passed through formData rather than through the body to be more consistent with how regular files are added

2022-12-05 22:05 UTC, anjor commented on handlers.go
> +	contents.GET("/contents", withUser(s.handleListContent))
Shouldn't these be behind /api/v2 ?

2022-12-05 22:14 UTC, anjor requested changes
We should not delete the v1 endpoints. They should still be around. The new endpoints should be under a v2 path.

Separately, I think uploadType should be an enum

2022-12-06 14:50 UTC, gmelodie commented
@kelindi I'm trying not to change too much. I think it's about balance.

2022-12-06 18:25 UTC, kelindi commented
@gmelodie I think it would add some more consistency when uploading a file, which would be better for dx. If I am understanding it correctly, the current route you have is the same no matter the file and then it figures out what the case is based on the file? If that is the case it would make more sense to have the request be formatted the same when uploading a regular file or a car file.

2022-12-08 17:41 UTC, gmelodie commented
Closing in favor of #716

2022-12-08 17:41 UTC, closed without merging