implement an upload proxy
application-research/estuary pull request #74
Opened 2021-11-04 14:32 UTC by whyrusleeping

This way we can have people just upload things to `upload.estuary.tech` and it will pick the right shuttle to hit. For people uploading *lots* of data, the will still want to go direct to a shuttle, but this works for more 'normal' users.

2021-11-04 20:08 UTC, elijaharita approved these changes
my 3 brain cells don't notice any particular issues looking through. this'll be really nice to have!

2021-11-11 15:54 UTC, ribasushi requested changes
Few missing error checks, the rest looks legit

2021-11-11 15:54 UTC, ribasushi commented on cmd/shuttle-proxy/main.go
> +	io.Copy(c.Response().Writer, resp.Body)
no error checks...?

2021-11-11 15:54 UTC, ribasushi commented on cmd/shuttle-proxy/main.go
> +	io.Copy(c.Response().Writer, resp.Body)
same: no error checks...

2021-11-29 21:00 UTC, merged